<a href="https://colab.research.google.com/github/Ann-Bond-coder/Artificial-intelligence/blob/main/Bondarenko_AI(lab3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Варіант 17

In [ ]:
# Виконати імпорт необхідних бібліотек.
import pandas as pd
import numpy as np
import os
from sklearn.impute import SimpleImputer

In [ ]:
# Виконати підключення до Google Drive, створити необхідні змінні 
# для зберігання шляхів до каталогів з данними.
# Вивести інформацію про вміст каталогу з данними.
from google.colab import drive
drive.mount('/content/gdrive')
original_path = '/content/gdrive/My Drive/Colab Notebooks/data/'

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [ ]:
# Створити змінну для зберігання шляху до файлу з данними.
path = os.path.join(original_path, 'ratings_withoutHeaders.csv')

In [ ]:
# Зчитати дані з файлу у масив NumPy.
data = pd.read_csv(path).astype(float)
data_np = np.array(data)
print(data_np)

[[1.0000e+00 4.3900e+02 3.0000e+00]
 [1.0000e+00 5.8800e+02 5.0000e+00]
 [1.0000e+00 1.1690e+03 4.0000e+00]
 ...
 [1.0000e+04 4.9383e+04 5.0000e+00]
 [1.0000e+04 5.0124e+04 5.0000e+00]
 [1.0000e+04 5.1328e+04 1.0000e+00]]


In [ ]:
# Вивести кількість строк та стовбців.
data_np.shape

(981755, 3)

In [ ]:
# Написати функцію додавання у набір данних необхідної кількості (%) пропущених значень у випадковій позиції. Параметри функції: 
# оригінальний набір данних та процент пропущених значень заданий у вигляді дійсного числа.

def add_NaNs(original_data, nan_percent):
    count = int(original_data.size * nan_percent)
    nan_positions = np.random.choice(original_data.size, count, replace=False)
    original_data.values.flat[nan_positions] = np.nan
    return original_data

In [ ]:
# Утворити новий набір даних з пропущеними значеннями (% пропущених значень - по варіанту = №варіанта + 50).
add_NaNs(data, 0.67)

1      314    5
0           NaN      NaN  3.0
1           NaN      NaN  NaN
2           1.0   1169.0  4.0
3           1.0      NaN  NaN
4           NaN      NaN  NaN
...         ...      ...  ...
981750      NaN      NaN  NaN
981751      NaN      NaN  4.0
981752  10000.0  49383.0  NaN
981753  10000.0      NaN  5.0
981754  10000.0  51328.0  NaN

[981755 rows x 3 columns]

In [ ]:
# Перевірити наявність NaN значень у отриманому наборі.
if(data.isnull().any().any()):
  print("Є значення NaN. Кількість: ", data.isnull().sum().sum(), "; всього кількість значень: ", data.size)
else:
  print("У таблиці не має значення NaN.")

Є значення NaN. Кількість:  1973327 ; всього кількість значень:  2945265


In [ ]:
# Обрати тип Strategy для створення екземпляру класу SimpleImputer за варіантом:
# непарні - strategy='constant'

imputer = SimpleImputer(missing_values = np.nan, strategy='constant', fill_value=0)
new_data = pd.DataFrame(imputer.fit_transform(data_np), columns=data.columns)

if(new_data.isnull().any().any()):
  print("Є значення NaN. Кількість: ", data.isnull().sum().sum(), "; всього кількість значень: ", data.size)
else:
  print("У таблиці не має значення NaN.")

У таблиці не має значення NaN.
